### PR TITLE
Use require.resolve() to locate livereload

### PR DESCRIPTION
**Pull request by benelsen**
Should fix problems with npm@3 and its "flat" node_modules.

### CODE REVIEW

**Comment by shama** [comment]
Thanks!

**Comment by JonnyBurger** [comment]
Thanks for this @benelsen! 
This should probably get a release before npm@3 will become default and livereload gets broken.

**Comment by Rowno** [comment]
FYI, npm@3 is now the default and this fix still hasn't been released.

**Comment by iamkevinv** [comment]
@shama / @mklabs ...as per @Rowno's comment, could the patch please be published for npm?

**Comment by elwayman02** [comment]
:+1:

**Pull request merged**
