### PR TITLE
Add reloadOnMissingCSS option, see livereload-js.

### PR DESCRIPTION
**Pull request by STRML**
Corresponding `livereload-js` PR: https://github.com/livereload/livereload-js/pull/41

### CODE REVIEW

**Comment by shama** [comment]
Waiting on a response from https://github.com/livereload/livereload-js/pull/41

**Comment by mklabs** [comment]
Hi guys, we may put this on hold since livereload/livereload-js#41 is on hold as well.

I'm thinking about forking livereload-js to enable us more freedom in the client side. And probably port it to ES6 and babel instead of coffee.

**Comment by elwayman02** [comment]
👍 on forking livereload-js, seems abandoned. Double 👍 on moving to ES6/babel, yay!

**Comment by mklabs** [comment]
Hi @STRML I'm sorry but I'll close your PR for the moment. As soon as we can have updates from livereloadjs or decide to make and build our own version of livereloadjs, we may reconsider this option.

I hope you understand.

**Comment by STRML** [comment]
Thanks - but if you consider this on hold, why not keep it open and label
rather than close, where it could be lost?

**Comment by mklabs** [comment]
Fine, let's keep it opened. This was just in order to clean up old issues / PR

**Comment by elwayman02** [comment]
@STRML might want to rebase while we're waiting, so it's good to go when the upstream gets resolved.

**Comment by elwayman02** [comment]
@STRML would you mind resolving conflict on this branch with a rebase? We finally have a maintainer active in livereload-js and I'm hopeful we can get your upstream PR merged soon so we can finally land this feature!

**Comment by STRML** [comment]
@elwayman02 Rebased it - 👍

**Comment by elwayman02** [comment]
Awesome, thanks! I'll do my best to keep an eye on the upstream PR and get that into tiny-lr asap.

**Pull request merged**
