### PR TITLE
Set host as 127.0.0.1 if host is undefined

### PR DESCRIPTION
**Pull request by davidyen1124**
Only user in localhost can use livereload api.

### CODE REVIEW

**Comment by shama** [comment]
Could you describe the need for this a bit more? Thanks!

**Comment by davidyen1124** [comment]
Server binds to `0.0.0.0` by default.
I think it's dangerous because anyone on same network can send requests to the `tiny-lr` server.

**Comment by shama** [comment]
Could you describe more technical details on how a default `0.0.0.0` server is dangerous? Keep in mind, enabling a live reload server in a production environment to begin with is not advised; live reload is for development.

I believe it currently defaults to `0.0.0.0` for convenience to those developing on remote servers. Which seems a lot more common use case than worrying about someone on your network triggering your live reload. But maybe I'm missing the big security concern here?

**Comment by davidyen1124** [comment]
Oops I forget about remote server.
Thanks for your answer.

**Comment by shama** [comment]
Thanks!

**Pull request closed without merging**
