### PR TITLE
Allow error(undefined)

### PR DESCRIPTION
**Pull request by Polyergic**
Using `ionic serve` occasionally crashes with output that calls for this fix, e.g.:

```
/full/path/to/project/node_modules/tiny-lr/src/server.js:266
      console.error('... Uhoh. Got error %s ...', e.message);
                                                   ^

TypeError: Cannot read property 'message' of undefined
```

### CODE REVIEW

**Comment by Polyergic** [comment]
Related but report to ionic: https://github.com/ionic-team/ionic/issues/12191

**Comment by elwayman02** [comment]
@Polyergic this PR has some linting errors. I'll be happy to merge once the build is green!

**Comment by Polyergic** [comment]
I cannot reproduce the error.  Here is the output I get from `npm test`:

```
> tiny-lr@1.0.5 test /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr
> npm run eslint && npm run mocha


> tiny-lr@1.0.5 eslint /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr
> eslint . --debug

  eslint:cli Running on files +0ms
  eslint:ignored-paths Looking for ignore file in /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr +65ms
  eslint:ignored-paths Loaded ignore file /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintignore +3ms
  eslint:ignored-paths Adding /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintignore +0ms
  eslint:glob-util Creating list of files to process. +1ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/app.js +21ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/app.js +2ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/app.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/package.json +5ms
  eslint:config-file Loading package.json config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/package.json +1ms
  eslint:config-file Loading JSON config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/package.json +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +1ms
  eslint:config-file Loading config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading standard +111ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/node_modules/eslint-config-standard/index.js +2ms
  eslint:config Using /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +230ms
  eslint:config Merging command line environment settings +1ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment es6 +1ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment mocha +1ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/server.js +117ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/server.js +0ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/server.js +1ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/client.js +27ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/client.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/client.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading standard +1ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/node_modules/eslint-config-standard/index.js +1ms
  eslint:config Using /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +2ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment es6 +1ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment mocha +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/index.js +73ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/index.js +0ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/index.js +0ms
  eslint:config Using config from cache +1ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/server.js +37ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/server.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/server.js +0ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/client.js +125ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/client.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/client.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading standard +1ms
  eslint:config-file Attempting to resolve eslint-config-standard +1ms
  eslint:config-file Loading JS config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/node_modules/eslint-config-standard/index.js +0ms
  eslint:config Using /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +2ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment es6 +0ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment mocha +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/helpers/listen.js +21ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/helpers/listen.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/helpers/listen.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading standard +1ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/node_modules/eslint-config-standard/index.js +0ms
  eslint:config Using /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +3ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment es6 +0ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment mocha +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/http.js +15ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/http.js +2ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/http.js +0ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/middleware.js +11ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/middleware.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/middleware.js +1ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/server.js +58ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/server.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/server.js +0ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Linting complete in: 934ms +42ms

> tiny-lr@1.0.5 mocha /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr
> npm run babel && mocha --reporter spec src_test/


> tiny-lr@1.0.5 babel /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr
> babel lib/ -d src && babel test/ -d src_test/

lib/client.js -> src/client.js
lib/index.js -> src/index.js
lib/server.js -> src/server.js
test/client.js -> src_test/client.js
test/helpers/listen.js -> src_test/helpers/listen.js
test/http.js -> src_test/http.js
test/middleware.js -> src_test/middleware.js
test/server.js -> src_test/server.js


  tiny-lr
    ✓ accepts ws clients
    ✓ properly cleans up established connection on exit

  mocha spec examples
    tinylr
      ✓ GET /

  Express Middleware
    GET /
      ✓ respond with nothing, but respond
      ✓ unknown route are noop with middlewares, next-ing
    GET /changed
      ✓ with no clients, no files
      ✓ with no clients, some files
    POST /changed
      ✓ with no clients, no files
      ✓ with no clients, some files
    POST /alert
      ✓ with no clients, no message
      ✓ with no clients, some message
    GET /livereload.js
      ✓ respond with livereload script
    GET /kill
      ✓ shutdown the server

  tiny-lr
    GET /
      ✓ respond with nothing, but respond
      ✓ unknown route respond with proper 404 and error message
    GET /changed
      ✓ with no clients, no files
      ✓ with no clients, some files
    POST /changed
      ✓ with no clients, no files
      ✓ with no clients, some files
    POST /alert
      ✓ with no clients, no message
      ✓ with no clients, some message
    GET /livereload.js
      ✓ respond with livereload script
    GET /kill
      ✓ shutdown the server


  23 passing (269ms)

GSU-ssterling3:tiny-lr ssterling3$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
GSU-ssterling3:tiny-lr ssterling3$ npm test

> tiny-lr@1.0.5 test /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr
> npm run eslint && npm run mocha


> tiny-lr@1.0.5 eslint /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr
> eslint . --debug

  eslint:cli Running on files +0ms
  eslint:ignored-paths Looking for ignore file in /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr +45ms
  eslint:ignored-paths Loaded ignore file /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintignore +2ms
  eslint:ignored-paths Adding /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintignore +0ms
  eslint:glob-util Creating list of files to process. +1ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/app.js +21ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/app.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/app.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/package.json +5ms
  eslint:config-file Loading package.json config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/package.json +1ms
  eslint:config-file Loading JSON config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/package.json +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +1ms
  eslint:config-file Loading config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading standard +99ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/node_modules/eslint-config-standard/index.js +1ms
  eslint:config Using /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +268ms
  eslint:config Merging command line environment settings +1ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment es6 +1ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment mocha +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/server.js +109ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/server.js +0ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/examples/express/server.js +0ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/client.js +21ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/client.js +0ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/client.js +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading standard +1ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/node_modules/eslint-config-standard/index.js +0ms
  eslint:config Using /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +3ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment es6 +0ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment mocha +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/index.js +66ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/index.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/index.js +0ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/server.js +31ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/server.js +2ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/lib/server.js +0ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/client.js +133ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/client.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/client.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading standard +1ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/node_modules/eslint-config-standard/index.js +1ms
  eslint:config Using /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +2ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment es6 +0ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment mocha +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/helpers/listen.js +24ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/helpers/listen.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/helpers/listen.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +0ms
  eslint:config-file Loading standard +1ms
  eslint:config-file Attempting to resolve eslint-config-standard +0ms
  eslint:config-file Loading JS config file: /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/node_modules/eslint-config-standard/index.js +0ms
  eslint:config Using /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/.eslintrc +3ms
  eslint:config Merging command line environment settings +0ms
  eslint:config-ops Apply environment settings to config +0ms
  eslint:config-ops Creating config for environment es6 +0ms
  eslint:config-ops Creating config for environment node +0ms
  eslint:config-ops Creating config for environment mocha +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/http.js +15ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/http.js +1ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/http.js +0ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/middleware.js +11ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/middleware.js +0ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/middleware.js +0ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Processing /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/server.js +46ms
  eslint:cli-engine Linting /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/server.js +0ms
  eslint:config Constructing config for /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr/test/server.js +1ms
  eslint:config Using config from cache +0ms
  eslint:cli-engine Linting complete in: 909ms +27ms

> tiny-lr@1.0.5 mocha /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr
> npm run babel && mocha --reporter spec src_test/


> tiny-lr@1.0.5 babel /Users/ssterling3/Documents/2017/IIT/Deps/tiny-lr
> babel lib/ -d src && babel test/ -d src_test/

lib/client.js -> src/client.js
lib/index.js -> src/index.js
lib/server.js -> src/server.js
test/client.js -> src_test/client.js
test/helpers/listen.js -> src_test/helpers/listen.js
test/http.js -> src_test/http.js
test/middleware.js -> src_test/middleware.js
test/server.js -> src_test/server.js


  tiny-lr
    ✓ accepts ws clients
    ✓ properly cleans up established connection on exit

  mocha spec examples
    tinylr
      ✓ GET /

  Express Middleware
    GET /
      ✓ respond with nothing, but respond
      ✓ unknown route are noop with middlewares, next-ing
    GET /changed
      ✓ with no clients, no files
      ✓ with no clients, some files
    POST /changed
      ✓ with no clients, no files
      ✓ with no clients, some files
    POST /alert
      ✓ with no clients, no message
      ✓ with no clients, some message
    GET /livereload.js
      ✓ respond with livereload script
    GET /kill
      ✓ shutdown the server

  tiny-lr
    GET /
      ✓ respond with nothing, but respond
      ✓ unknown route respond with proper 404 and error message
    GET /changed
      ✓ with no clients, no files
      ✓ with no clients, some files
    POST /changed
      ✓ with no clients, no files
      ✓ with no clients, some files
    POST /alert
      ✓ with no clients, no message
      ✓ with no clients, some message
    GET /livereload.js
      ✓ respond with livereload script
    GET /kill
      ✓ shutdown the server


  23 passing (245ms)
```

**Comment by Polyergic** [comment]
The errors in the [details](https://travis-ci.org/mklabs/tiny-lr/builds/247957698?utm_source=github_status&utm_medium=notification) are
```
/home/travis/build/mklabs/tiny-lr/lib/server.js
  203:5   error  Expected space(s) after "if"                 keyword-spacing
  203:7   error  There should be no spaces inside this paren  space-in-parens
  203:22  error  Strings must use singlequote                 quotes
  203:34  error  There should be no spaces inside this paren  space-in-parens
```
all reported on line 203 of `lib/server.js`,
```
    console.error('... Uhoh. Got error %s ...', e.message);
```
which doesn't seem related to those errors.

**Comment by Polyergic** [comment]
Nevermind, git did something stupid when it created the fork for what was supposed to be a trivial edit.  After another hour of figuring out your quirks and githubs quirks I think it's fixed.

**Pull request merged**
