### PR TITLE
update livereload client (closes #132)

### LINKED ISSUE #132: Update livereload-js to 3x

### PR DESCRIPTION
**Pull request by smhg**

### CODE REVIEW

**Comment by mr-wildcard** [comment]
looking forward to that :)

`Options.extract` in livereload-js@^2 method is not reliable as it doesn't correctly parse the `src` attribute of the script containing `/livereload.js` (In my case, `port` cannot be extracted).

**Comment by smhg** [comment]
@mr-wildcard would you be willing to open an issue with an example in the [livereload-js](https://github.com/livereload/livereload-js) repo? Thanks!

**Comment by mr-wildcard** [comment]
@smhg this has already been fixed a long time ago in livereload-js@^3. I was just giving another reason to upgrade this tiny-lr dependency ;)

**Comment by elwayman02** [comment]
@smhg are there any breaking changes between livereload 2 and 3?

**Comment by smhg** [comment]
The only thing I would be aware of is the lack of ancient browser support (IE6-9).
Prior to v3 the library was built by the Coffeescript compiler and I have no idea how far back browser support went with those builds.

**Pull request merged**
