### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ntwb**
The primary 2 updates are for `qs` and `wd`
• `qs`: `~5.1.0` -> `~6.0.1`
• `wd`: `^0.3.12` -> `^0.4.0`

The remaining are covered by existing semver though when in Rome...

### CODE REVIEW

**Comment by elwayman02** [comment]
@ntwb it looks like the build is failing...related to the new `qs` version using `const` in strict mode. I don't think earlier versions of node support ES6 syntax, so we need to either deprecate support for those versions or keep `qs` on the current version. For now, can you rollback the `qs` upgrade and submit a separate PR where we can discuss the pros and cons of that upgrade while still being able to take advantage of these other dependency updates?

Also, sorry about taking so long to get back to you...if there are some more new versions since you submitted this PR, feel free to update them as well. I'll merge once we have a passing build.

**Comment by andersevenrud** [comment]
They actually refactored the `const` in https://github.com/ljharb/qs/commit/224c8af8fc8abf48fd9ded33a38997a1d942c1c1

So this is probably "safe" now

**Comment by ntwb** [comment]
Apologies it took me a while to get back to this, refreshed the pull request update all the dependancies except `qs`

**Comment by ntwb** [comment]
Added a PR for `qs` v6.x https://github.com/mklabs/tiny-lr/pull/101

**Comment by elwayman02** [comment]
@ntwb can you rebase this really quick? Build looks good, I'll merge. Thanks!

**Comment by ntwb** [comment]
Rebase went horribly wrong, fresh pull request in #102

**Pull request closed without merging**
